site_name: High-Pressure Laser Floating Zone Lab
site_url: https://example.com/
nav:
    - Welcome: index.md
    - Furnace Design: about.md
    - Sample Preparation: sampleprep.md
    - Equipment Setup: poweron.md
    - Imaging Control: imaging.md
    - Laser Control: lasercontrol.md
    - Translator Control: translatorcontrol.md
    - Sample Mounting and Alignment: samplemounting.md
    - Sealing the Chamber: sealing.md
    - Pressurizing the Chamber: gascontrol.md
    - Beginning a Growth: growth.md
    - Ending a Growth: endgrowth.md
    - Opening and Cleaning the Chamber: postgrowth.md
    - Maintenance: maintenance.md

theme: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js